version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
          key: project-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: project-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: ESLint
          command: yarn run eslint -- .
      # - run:
      #     name: Flow type-checking
      #     command: yarn run flow
      - run:
          name: Compile src -> dist
          command: yarn run build
      - store_artifacts:
          path: dist/
          path: .serverless/
      - deploy:
          name: Maybe deploy to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run deploy:prod
            fi
